FROM node:22-alpine

WORKDIR /app

# Install OS deps and copy package definitions
RUN apk add --no-cache libc6-compat openssl
COPY package.json package-lock.json ./
COPY apps/web/package.json apps/web/
COPY packages/database/package.json packages/database/
COPY packages/types/package.json packages/types/

RUN npm install

# Copy entire repo
COPY . .

# Generate DB client
RUN npm run db:generate --workspace=packages/database

# Build web app
RUN npm run build --workspace=apps/web

EXPOSE 3000

CMD ["npm", "run", "start", "--workspace=apps/web"]
