FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl
COPY package.json package-lock.json ./
COPY apps/worker/package.json apps/worker/
COPY packages/database/package.json packages/database/
COPY packages/types/package.json packages/types/

RUN npm install

COPY . .

RUN npm run db:generate --workspace=packages/database

CMD ["npm", "run", "start", "--workspace=apps/worker"]
